# Generated by Django 4.2.6 on 2023-10-27 21:16

from django.db import migrations, models
import urlshortner.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=700, validators=[urlshortner.models.OptionalSchemeURLValidator()]),
        ),
    ]
